from __future__ import annotations
from pathlib import Path
import tempfile
import pandas as pd
import matplotlib.pyplot as plt
from pptx import Presentation
from pptx.util import Inches


def _replace_text(slide, replacements):
    for shape in slide.shapes:
        if not hasattr(shape, 'text_frame'):
            continue
        txt = shape.text
        new = txt
        for old, val in replacements.items():
            new = new.replace(old, str(val))
        if new != txt:
            shape.text = new


def _find_shape(slide, text):
    for shape in slide.shapes:
        if hasattr(shape, 'text') and shape.text.strip() == text:
            return shape
    return None


def _set_shape_text(slide, old_text, new_text):
    s = _find_shape(slide, old_text)
    if s is not None:
        s.text = str(new_text)
        return True
    return False


def _add_chart(slide, df, x, y, w, h, kind='bar', title=None, rotate=0):
    if df is None or df.empty:
        return
    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as f:
        path = f.name
    fig = plt.figure(figsize=(7, 3.0), dpi=180)
    ax = fig.add_subplot(111)
    d = df.copy()
    labels = d.iloc[:,0].astype(str).tolist()
    vals = pd.to_numeric(d.iloc[:,1], errors='coerce').fillna(0).tolist()
    if kind == 'pie':
        ax.pie(vals, labels=labels, autopct='%1.0f%%', textprops={'fontsize':7})
    elif kind == 'line':
        ax.plot(range(len(vals)), vals, marker='o')
        ax.set_xticks(range(len(vals))); ax.set_xticklabels(labels, rotation=rotate, ha='right', fontsize=7)
        ax.set_ylabel('Cases')
    else:
        ax.bar(labels, vals)
        ax.tick_params(axis='x', labelrotation=rotate, labelsize=7)
        ax.set_ylabel('Cases')
    if title: ax.set_title(title, fontsize=10)
    ax.grid(axis='y', alpha=.2)
    fig.tight_layout()
    fig.savefig(path, bbox_inches='tight', transparent=True)
    plt.close(fig)
    slide.shapes.add_picture(path, Inches(x), Inches(y), Inches(w), Inches(h))
    Path(path).unlink(missing_ok=True)


def _table_rows(table, rows):
    for r, values in enumerate(rows, start=1):
        if r >= len(table.rows): break
        for c, value in enumerate(values):
            if c < len(table.columns):
                table.cell(r,c).text = str(value)


def generate_powerpoint(template_path: str | Path, output_path: str | Path, analysis: dict, intelligence: dict, municipality: str, reporting_date, period_covered: str, close_time: str):
    prs = Presentation(str(template_path))
    summary = analysis['summary']
    corridor = municipality or 'OOP Corridor'
    date_str = reporting_date.strftime('%d %B %Y') if hasattr(reporting_date, 'strftime') else str(reporting_date)
    period = period_covered or 'Not specified'
    close = close_time if isinstance(close_time, str) else close_time.strftime('%H:%M')
    coverage = f"{summary['ward_coverage_pct']:.1f}%" if summary['ward_coverage_pct'] is not None else 'Not configured'
    covered = summary['distinct_wards']
    total = summary['total_wards'] if summary['total_wards'] else '—'
    missing = summary['missing_wards'] if summary['missing_wards'] is not None else '—'
    voc = 'Not supplied'
    status = 'GREEN' if summary['invalid_case_records'] == 0 and (summary['ward_coverage_pct'] in (None, 100)) else 'AMBER'

    footer = f"{corridor} | INTERNAL OOP OPERATIONS REPORTING | {date_str} | {close}"
    common = {'[CORRIDOR NAME]': corridor, '[MUNICIPALITIES / REGIONS]': corridor, '[REPORTING DATE]': date_str, '[PERIOD COVERED]': period, '[DATA CLOSE TIME]': close, '[RAG]': status}
    for slide in prs.slides:
        _replace_text(slide, common)
        _set_shape_text(slide, f"{corridor} | INTERNAL SDI OPERATIONS REPORTING | {date_str} | {close}", footer)
        _set_shape_text(slide, 'Template: replace all [bracketed] fields and sample chart data', 'Generated by OOP Corridor Reporting System')

    # Slide 1
    s = prs.slides[0]
    _set_shape_text(s, '[##]', f"{summary['valid_cases']:,}")
    _set_shape_text(s, '[##/##]', f"{covered}/{total}")
    _set_shape_text(s, '[##%]', coverage)
    _set_shape_text(s, '[##]', str(missing))
    _set_shape_text(s, '[RAG]', status)
    _set_shape_text(s, 'VOC ready / done', 'VOC ready / done')
    # There are multiple [##] placeholders; set by position for the first slide.
    vals = [f"{summary['valid_cases']:,}", f"{covered}/{total}", coverage, str(missing), voc, status]
    placeholders = [sh for sh in s.shapes if hasattr(sh,'text') and sh.text.strip() in {'[##]','[##/##]','[##%]','[RAG]'}]
    for sh, val in zip(placeholders, vals): sh.text = val

    # Slide 2
    s = prs.slides[1]
    text_shapes = [sh for sh in s.shapes if hasattr(sh,'text')]
    _set_shape_text(s, '[##] valid cases opened [##] of [target] wards ([##%]). [Best-performing municipality/region] leads coverage; [largest gap] carries the largest missing-ward load.',
                    f"{summary['valid_cases']:,} valid cases are represented across {covered} of {total} configured wards ({coverage}).")
    _set_shape_text(s, '[Today / week-to-date] added [##] new wards and [##] cases compared with [previous close]. Note material increases or flat movement only.',
                    f"The current extract contains {summary['records']:,} records. Reporting-period comparison will be added once a prior-close dataset is supplied.")
    _set_shape_text(s, '[##] wards remain uncovered. Prioritise wards carried over from the previous close and any channel/time gaps affecting coverage.',
                    f"{missing} wards remain outside the represented-ward list based on the configured total. Prioritise validation of the missing-ward queue before circulation.")
    _set_shape_text(s, 'Replace with cases and new wards by day.', 'Cases by available Created On date')
    if analysis['dates'].get('available'):
        d=analysis['dates']['by_date'][['date','cases']].copy(); d['date']=d['date'].astype(str)
        _add_chart(s,d.head(10),0.75,3.85,3.6,1.55,'line','Cases by day',45)
    _set_shape_text(s, 'Recommended focus', 'Recommended focus')
    _set_shape_text(s, 'Assign missing wards by municipality/region.\nProtect high-yield calling times.\nMove detailed exceptions to addendum.',
                    'Validate missing wards against the official ward register.\nProtect peak intake hours.\nKeep detailed exceptions in the addendum.')

    # Slide 3
    s=prs.slides[2]
    _set_shape_text(s, 'Replace with stacked bars by municipality/region.', 'Represented vs missing wards')
    # Generic single-area table; multi-area mapping comes later when municipality field/reference mapping is added.
    rows = [[corridor, total, covered, missing, coverage], ['Total', total, covered, missing, coverage]]
    # Fill the four data rows by exact placeholder positions.
    ph = [sh for sh in s.shapes if hasattr(sh,'text') and sh.text.strip() in {'[Municipality/Region A]','[Municipality/Region B]','[Municipality/Region C]','Total'}]
    data_by_y = sorted([sh for sh in ph], key=lambda sh: sh.top)
    # Find adjacent value placeholders and populate by row based on y positions.
    for sh in s.shapes:
        if hasattr(sh,'text') and sh.text.strip() == '[Municipality/Region A]': sh.text=corridor
        elif hasattr(sh,'text') and sh.text.strip() == '[Municipality/Region B]': sh.text='Not available from mapped municipality field'
        elif hasattr(sh,'text') and sh.text.strip() == '[Municipality/Region C]': sh.text='Not available from mapped municipality field'
    # Replace remaining numeric placeholders by their vertical row.
    row_values={2:(total,covered,missing,coverage),2.71:(None,None,None,None),3.13:(None,None,None,None),3.56:(total,covered,missing,coverage)}
    for sh in s.shapes:
        if not hasattr(sh,'text'): continue
        t=sh.text.strip(); y=round(sh.top/914400,2)
        if t in {'[##]','[##%]'} and y in {2.27,2.71,3.13,3.56}:
            if y==2.27:
                # cycle target/covered/missing/% based x
                x=round(sh.left/914400,2); vals={2.74:total,3.56:covered,4.42:missing,5.28:coverage}
                if x in vals: sh.text=str(vals[x])
            elif y==3.56:
                x=round(sh.left/914400,2); vals={2.74:total,3.56:covered,4.42:missing,5.28:coverage}
                if x in vals: sh.text=str(vals[x])
    _add_chart(s,pd.DataFrame({'label':[corridor],'cases':[covered]}),6.8,2.15,5.3,1.35,'bar','Wards represented',0)
    _set_shape_text(s, 'The addendum must carry the full accounted and missing ward list with area/sub-place names, carried-over flags and assigned owner.',
                    'The addendum should carry the full accounted and missing ward list, validation flags and assigned owner. This V1 dataset supports represented-ward counts; official missing-ward names require a ward master list.')

    # Slide 4
    s=prs.slides[3]
    _set_shape_text(s,'Replace with cases by channel or channel share.','Cases by channel')
    if not analysis['channel'].empty:
        _add_chart(s,analysis['channel'][['value','cases']].head(6),7.15,2.15,5.0,1.35,'bar','Channel mix',45)
    _set_shape_text(s,'Replace with cases by hour and cumulative new wards.','Hourly case activity')
    if analysis['dates'].get('available'):
        _add_chart(s,analysis['dates']['by_hour'][['hour','cases']],0.75,4.72,5.5,0.9,'line','Cases by hour',45)
    # Channel table rows
    ch=analysis['channel'].head(4)
    for idx in range(4):
        if idx < len(ch):
            r=ch.iloc[idx]; vals=[str(r['value']),f"{int(r['cases']):,}",f"{r['share_pct']:.1f}%",'—','Review timing/coverage']
        else: vals=['—','—','—','—','—']
        y=round((2.27+idx*0.43),2)
        for sh in s.shapes:
            if hasattr(sh,'text') and round(sh.top/914400,2)==y:
                x=round(sh.left/914400,2); mapping={0.59:vals[0],1.84:vals[1],2.64:vals[2],3.29:vals[3],4.19:vals[4]}
                if x in mapping: sh.text=mapping[x]

    # Slide 5
    s=prs.slides[4]
    _set_shape_text(s,'Replace with top 5-8 services by cases.','Top demand categories')
    if not analysis['category1'].empty:
        _add_chart(s,analysis['category1'][['value','cases']].head(6),0.75,2.15,4.8,1.45,'bar','Top Case Category 1',45)
        cat=analysis['category1'].head(3)
        for idx in range(3):
            if idx<len(cat):
                r=cat.iloc[idx]; vals=[str(r['value']),f"{int(r['cases']):,}",f"{r['share_pct']:.1f}%",'Demand indicator']
            else: vals=['—','—','—','—']
            y=round(2.31+idx*0.46,2)
            for sh in s.shapes:
                if hasattr(sh,'text') and round(sh.top/914400,2)==y:
                    x=round(sh.left/914400,2); mp={6.19:vals[0],8.24:vals[1],8.94:vals[2],9.59:vals[3]}
                    if x in mp: sh.text=mp[x]
    _set_shape_text(s,'List services not yet seen or single-service wards that require probing during callbacks. This keeps the slide operational without overcrowding it.',
                    'Use the addendum to identify low-volume/single-service wards and services requiring callback probing.')

    # Slide 6
    s=prs.slides[5]
    vals=['Not supplied','Not supplied','Not available','Not available','Not supplied']
    for sh in s.shapes:
        if hasattr(sh,'text') and sh.text.strip() in {'[##]','[##%]','[Status]'}:
            sh.text=vals.pop(0) if vals else 'Not supplied'
    _set_shape_text(s,'If no date-aligned VOC dataset is supplied, report availability as \'Not supplied\' and do not infer happiness, effort, satisfaction or NPS. Put anomaly detail in the addendum.',
                    'No date-aligned VOC dataset was supplied with this V1 extract. Happiness, effort, satisfaction and NPS are therefore not inferred.')

    # Slide 7
    s=prs.slides[6]
    if audience_view:
        audience_name = audience_view.get("audience", "Executive management")
        _set_shape_text(s, "[State one clear management decision or escalation required.]", f"Audience: {audience_name}. Prioritise the highest-impact evidence-backed actions.")
    q=len(analysis['quality'])
    action_rows=[
        ('Missing wards','Ops lead','Next close',f'{missing} wards validated/assigned'),
        ('Channel/time gap','Supervisor','Next operating window','Peak hours protected'),
        ('VOC queue','VOC lead','When VOC source is supplied','VOC-ready dataset'),
        ('Data quality','Data lead','Before circulation',f'{q} quality findings reviewed'),
    ]
    ys=[2.42,2.94,3.46,3.98]
    for vals,y in zip(action_rows,ys):
        for sh in s.shapes:
            if hasattr(sh,'text') and round(sh.top/914400,2)==y:
                x=round(sh.left/914400,2); mp={0.59:vals[0],2.24:vals[1],3.59:vals[2],4.84:vals[3]}
                if x in mp: sh.text=str(mp[x])
    _set_shape_text(s,'[State one clear management decision or escalation required.]',
                    f'Confirm the {missing} unrepresented wards against the official ward register and assign the next operational follow-up.')
    _set_shape_text(s,'[State the only caveat that changes interpretation: data cut-off, missing source, or unresolved validation.]',
                    'The municipality field is not populated in the supplied extract; area-level breakdowns therefore require a validated municipality/ward reference mapping.')
    _set_shape_text(s,'Detailed graphs, accounted wards, missing wards, time logs and correction registers are attached separately.',
                    'Detailed graphs, accounted/missing ward lists, time logs, evidence and correction registers should be attached as the analytical addendum.')
    prs.save(str(output_path))
    return Path(output_path)
